DMT\KvK\Api\Model\CompanySearchV2Address:
  access_type: public_method
  properties:
    type:
      type: string
    street:
      type: string
    houseNumber:
      type: string
    houseNumberAddition:
      type: string
    postalCode:
      type: string
    city:
      type: string
    country:
      type: string