DMT\KvK\Api\Model\CompanyBasicV2ResultData:
  access_type: public_method
  properties:
    itemsPerPage:
      type: int
    startPage:
      type: int
    totalItems:
      type: int
    nextLink:
      type: string
    previousLink:
      type: string
    query:
      type: string
    items:
      type: array<DMT\KvK\Api\Model\CompanyBasicV2>