DMT\KvK\Api\Model\CompanyBasicV2:
  access_type: public_method
  properties:
    kvkNumber:
      type: string
    branchNumber:
      type: string
    rsin:
      type: string
    tradeNames:
      type: DMT\KvK\Api\Model\CompanySearchV2TradeNames
    hasEntryInBusinessRegister:
      accessor:
        getter: hasEntryInBusinessRegister
      type: bool
    hasNonMailingIndication:
      accessor:
        getter: hasNonMailingIndication
      type: bool
    isLegalPerson:
      accessor:
        getter: isLegalPerson
      type: bool
    isBranch:
      accessor:
        getter: isBranch
      type: bool
    isMainBranch:
      accessor:
        getter: isMainBranch
      type: bool
    addresses:
      type: array<DMT\KvK\Api\Model\CompanySearchV2Address>
    websites:
      type: array<string>