DMT\KvK\Api\Command\GetCompaniesBasicV2:
  properties:
    kvkNumber:
      - Regex:
          pattern: '~^\d{8}$~'
          message: invalid kvkNumber given
    branchNumber:
      - Regex:
          pattern: '~^\d{12}$~'
          message: invalid branchNumber given
    rsin:
      - Regex:
          pattern: '~^\d+$~'
          message: invalide rsin given
    postalCode:
      - Regex:
          pattern: '~^[1-9]\d{3}[A-Z]$~'
          message: invalid postalCode given